Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
      AccessControl: PublicRead

  IndexHtml:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${MyBucket}/*'

  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: my-origin
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          DefaultTTL: 300
          MaxTTL: 3600
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /404.html
            ResponseCode: 404
            ErrorCachingMinTTL: 0
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: my-origin
            DomainName: !GetAtt MyBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: my-rule
      Description: Automatically invalidate the landing page cache
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'Object Created'
          - 'Object Removed'
        detail:
          bucket:
            name:
              - !Ref MyBucket

  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-function
      Runtime: python3.8
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import boto3

          def handler(event, context):
              client = boto3.client("cloudfront")
              client.create_invalidation(
                  DistributionId="<Your-CloudFront-Distribution-ID>",
                  InvalidationBatch={
                      "Paths": {
                          "Quantity": 1,
                          "Items": ["/*"]
                      },
                      "CallerReference": "my-reference"
                  }
              )

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudFrontFullAccess

  MyEventTarget:
    Type: AWS::Events::Target
    Properties:
      Rule: !Ref MyEventRule
      TargetId: my-target
      Arn: !GetAtt MyFunction.Arn
